sudo: false

language: go

go:
  - "1.12"

git:
  depth: 1

before_install:
  # Homebrew
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - sudo apt-get install build-essential
  - echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/travis/.bash_profile
  - eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

install:
  # Install Hugo
  - brew install hugo

script:
  - git submodule init
  - git submodule update
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
