googleAnalytics = "UA-158767348-1"

baseURL = "https://clarkzhang0123.github.io/chongchongzainan"
languageCode = "zh-ch"
title = "重重灾难"
theme = "book"

[params]
  BookMenuBundle = '/menu'
  BookSearch = false